language: node_js
node_js:
    - 0.8
branches:
    only:
      - master
      - develop
<<<<<<< HEAD
before_install:
    - phantomjs --webdriver=10000 &
=======
>>>>>>> origin
before_script:
    - npm install -g grunt-cli